services:
  - type: web
    name: flask-site
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: "gunicorn app:app"
